=== donatellosantoro/Llunatic/lunaticEngine/build/classes/resources/de/expenseDB/expenseDB.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="expenseDB">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" name="companies" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="company" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" name="companyId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="companyName" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="city" nillable="true" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" name="projects" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="project" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" name="projectName" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="year" nillable="true" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" name="grants" nillable="false">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="grant" nillable="false">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" name="principalInvestigator" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="amount" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="sponsorId" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="projectRef" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="1" name="grantee" nillable="true" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:key name="key1">
      <xs:selector xpath=".//project"/>
      <xs:field xpath="projectName"/>
    </xs:key>
    <xs:key name="key2">
      <xs:selector xpath=".//company"/>
      <xs:field xpath="companyId"/>
    </xs:key>
    <xs:keyref name="keyRef1" refer="key1">
      <xs:selector xpath=".//grant"/>
      <xs:field xpath="projectRef"/>
    </xs:keyref>
    <xs:keyref name="keyRef2" refer="key2">
      <xs:selector xpath=".//grant"/>
      <xs:field xpath="grantee"/>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== donatellosantoro/Llunatic/lunaticEngine/misc/resources/de/expenseDB/expenseDB-instance.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<expenseDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="expenseDB.xsd">
  <companies>
    <company>
      <companyId>1</companyId>
      <companyName>Microsoft</companyName>
      <city>Seattle</city>
    </company>
    <company>
      <companyId>2</companyId>
      <companyName>IBM</companyName>
      <city>New York</city>
    </company>
    <company>
      <companyId>3</companyId>
      <companyName>Apple</companyName>
      <city>Cupertino</city>
    </company>
  </companies>
  <projects>
    <project>
      <projectName>SQL Server</projectName>
      <year>1980</year>
    </project>
    <project>
      <projectName>DB2</projectName>
      <year>1980</year>
    </project>
    <project>
      <projectName>Clio</projectName>
      <year>2000</year>
    </project>
  </projects>
  <grants>
    <grant>
      <principalInvestigator>Peter Parker</principalInvestigator>
      <amount>1000.0</amount>
      <sponsorId>5</sponsorId>
      <projectRef>SQL Server</projectRef>
      <grantee>1</grantee>
    </grant>
    <grant>
      <principalInvestigator>Frank Castle</principalInvestigator>
      <amount>5000.0</amount>
      <sponsorId>6</sponsorId>
      <projectRef>DB2</projectRef>
      <grantee>2</grantee>
    </grant>
    <grant>
      <principalInvestigator>Tony Stark</principalInvestigator>
      <amount>NULL</amount>
      <sponsorId>7</sponsorId>
      <projectRef>Clio</projectRef>
      <grantee>2</grantee>
    </grant>
    <grant>
      <principalInvestigator>Bruce Banner</principalInvestigator>
      <amount>5000</amount>
      <sponsorId>6</sponsorId>
      <projectRef>NULL</projectRef>
      <grantee>1</grantee>
    </grant>
  </grants>
</expenseDB>
