=== donatellosantoro/Llunatic/lunaticEngine/misc/resources/de/bookPublisher/bookPublisher-source.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="source">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="IBDBookSet" minOccurs="0" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IBDBook" maxOccurs="unbounded" minOccurs="0" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" nillable="false" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="LOCSet" minOccurs="0" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="LOC" maxOccurs="unbounded" minOccurs="0" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" nillable="false" type="xs:string"/>
										<xs:element name="publisher" nillable="false" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="IBLBookSet" minOccurs="0" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IBLBook" maxOccurs="unbounded" minOccurs="0" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" nillable="false" type="xs:string"/>
										<xs:element name="pubId" nillable="false" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="IBLPublisherSet" minOccurs="0" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="IBLPublisher" maxOccurs="unbounded" minOccurs="0" nillable="false">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" nillable="false" type="xs:string"/>
										<xs:element name="name" nillable="false" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== donatellosantoro/Llunatic/lunaticEngine/misc/resources/de/bookPublisher/bookPublisher-source-instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bookPublisher-source.xsd">
  <IBDBookSet>
    <IBDBook>
      <title>The Hobbit</title>
    </IBDBook>
    <IBDBook>
      <title>The Da Vinci Code</title>
    </IBDBook>
    <IBDBook>
      <title>The Lord of the Rings</title>
    </IBDBook>
  </IBDBookSet>
  <LOCSet>
    <LOC>
      <title>The Lord of the Rings</title>
      <publisher>Houghton</publisher>
    </LOC>
    <LOC>
      <title>The Catcher in the Rye</title>
      <publisher>Lb Books</publisher>
    </LOC>
  </LOCSet>
  <IBLBookSet>
    <IBLBook>
      <title>The Hobbit</title>
      <pubId>245</pubId>
    </IBLBook>
    <IBLBook>
      <title>The Catcher in the Rye</title>
      <pubId>901</pubId>
    </IBLBook>
  </IBLBookSet>
  <IBLPublisherSet>
    <IBLPublisher>
      <id>245</id>
      <name>Ballantine</name>
    </IBLPublisher>
    <IBLPublisher>
      <id>901</id>
      <name>Lb Books</name>
    </IBLPublisher>
  </IBLPublisherSet>  
</source>
